[target.mips-unknown-linux-musl]
linker = "/Users/sysop/.rustup/toolchains/1.74.0-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin/rust-lld"
rustflags = ["-C", "link-self-contained=yes", "-C", "linker-flavor=ld.lld", "-C", "relocation-model=static", "-C", "link-arg=-no-pie", "-L", "native=/tmp/mipslibs"]
